#ifndef ACTRAIL_ABI_FILE_PATH_H
#define ACTRAIL_ABI_FILE_PATH_H

#include "observation.h"

enum actrail_file_path_abi {
    ACTRAIL_FILE_EVENT_HEADER_SIZE = 128,
    ACTRAIL_FILE_EVENT_PRIMARY_PATH_SIZE = 384,
    ACTRAIL_FILE_PATH_ABI_MAX_BYTES = 256,
    ACTRAIL_FILE_PATH_COPY_MAX_BYTES = 255,
};

enum actrail_file_fd {
    ACTRAIL_FILE_FD_MISSING = 0xffffffff,
};

enum actrail_file_path_flags {
    ACTRAIL_FILE_PATH_CAPTURED = 1,
    ACTRAIL_FILE_PATH_TRUNCATED = 2,
    ACTRAIL_FILE_PATH_FAULT = 4,
};

enum actrail_file_path_role {
    ACTRAIL_FILE_PRIMARY_PATH = 0,
    ACTRAIL_FILE_SECONDARY_PATH = 1,
};

enum actrail_file_event_phase {
    ACTRAIL_FILE_PHASE_ENTER = 1,
    ACTRAIL_FILE_PHASE_EXIT = 2,
};

enum actrail_file_syscall_id {
    ACTRAIL_FILE_SYSCALL_OPEN = 1,
    ACTRAIL_FILE_SYSCALL_OPENAT = 2,
    ACTRAIL_FILE_SYSCALL_CREAT = 3,
    ACTRAIL_FILE_SYSCALL_UNLINK = 4,
    ACTRAIL_FILE_SYSCALL_UNLINKAT = 5,
    ACTRAIL_FILE_SYSCALL_RENAME = 6,
    ACTRAIL_FILE_SYSCALL_RENAMEAT = 7,
    ACTRAIL_FILE_SYSCALL_RENAMEAT2 = 8,
    ACTRAIL_FILE_SYSCALL_MKDIR = 9,
    ACTRAIL_FILE_SYSCALL_MKDIRAT = 10,
    ACTRAIL_FILE_SYSCALL_RMDIR = 11,
    ACTRAIL_FILE_SYSCALL_TRUNCATE = 12,
    ACTRAIL_FILE_SYSCALL_FTRUNCATE = 13,
    ACTRAIL_FILE_SYSCALL_MMAP = 14,
    ACTRAIL_FILE_SYSCALL_CLOSE = 15,
    ACTRAIL_FILE_SYSCALL_DUP = 16,
    ACTRAIL_FILE_SYSCALL_DUP2 = 17,
    ACTRAIL_FILE_SYSCALL_DUP3 = 18,
    ACTRAIL_FILE_SYSCALL_FCNTL = 19,
    ACTRAIL_FILE_SYSCALL_CHDIR = 20,
    ACTRAIL_FILE_SYSCALL_FCHDIR = 21,
    ACTRAIL_FILE_SYSCALL_OPENAT2 = 22,
    ACTRAIL_FILE_SYSCALL_PIPE = 23,
    ACTRAIL_FILE_SYSCALL_PIPE2 = 24,
    ACTRAIL_FILE_SYSCALL_SOCKETPAIR = 25,
    ACTRAIL_FILE_SYSCALL_READ_SUMMARY = 26,
    ACTRAIL_FILE_SYSCALL_CLOSE_RANGE = 27,
    ACTRAIL_FILE_SYSCALL_IOCTL_CLOEXEC = 28,
    ACTRAIL_FILE_SYSCALL_IOCTL_NCLOEXEC = 29,
};

enum actrail_file_syscall_arg_count {
    ACTRAIL_FILE_SYSCALL_ARGC_CHDIR = 1,
    ACTRAIL_FILE_SYSCALL_ARGC_CLOSE = 1,
    ACTRAIL_FILE_SYSCALL_ARGC_CLOSE_RANGE = 3,
    ACTRAIL_FILE_SYSCALL_ARGC_CREAT = 2,
    ACTRAIL_FILE_SYSCALL_ARGC_DUP = 1,
    ACTRAIL_FILE_SYSCALL_ARGC_DUP2 = 2,
    ACTRAIL_FILE_SYSCALL_ARGC_DUP3 = 3,
    ACTRAIL_FILE_SYSCALL_ARGC_FCHDIR = 1,
    ACTRAIL_FILE_SYSCALL_ARGC_FCNTL = 3,
    ACTRAIL_FILE_SYSCALL_ARGC_MKDIRAT = 3,
    ACTRAIL_FILE_SYSCALL_ARGC_MMAP = 6,
    ACTRAIL_FILE_SYSCALL_ARGC_OPEN = 3,
    ACTRAIL_FILE_SYSCALL_ARGC_OPENAT = 4,
    ACTRAIL_FILE_SYSCALL_ARGC_OPENAT2 = 4,
    ACTRAIL_FILE_SYSCALL_ARGC_PIPE = 1,
    ACTRAIL_FILE_SYSCALL_ARGC_PIPE2 = 2,
    ACTRAIL_FILE_SYSCALL_ARGC_RENAMEAT = 4,
    ACTRAIL_FILE_SYSCALL_ARGC_SOCKETPAIR = 4,
    ACTRAIL_FILE_SYSCALL_ARGC_UNLINKAT = 3,
};

enum actrail_file_ipc_fd_kind {
    ACTRAIL_FILE_IPC_FD_PIPE = 1,
    ACTRAIL_FILE_IPC_FD_UNIX_SOCKET = 2,
};

enum actrail_file_enter_descriptor {
    ACTRAIL_FILE_DESCRIPTOR_KIND_BITS = 16,
    ACTRAIL_FILE_DESCRIPTOR_SYSCALL_BITS = 16,
    ACTRAIL_FILE_DESCRIPTOR_KIND_MASK = 0xffff,
    ACTRAIL_FILE_DESCRIPTOR_SYSCALL_MASK = 0xffff,
    ACTRAIL_FILE_DESCRIPTOR_SYSCALL_SHIFT = 16,
    ACTRAIL_FILE_DESCRIPTOR_ARGC_SHIFT = 32,
};
struct actrail_file_event {
    __u32 kind;
    __u32 pid;
    __u32 tid;
    __u32 phase;
    __s64 result;
    __u64 trace_id;
    __u64 observed_ktime_ns;
    __u32 fd;
    __u32 aux;
    __u32 path_size;
    __u32 path_flags;
    __u32 secondary_path_size;
    __u32 secondary_path_flags;
    __u32 path_max_bytes;
    __u32 reserved;
    __u64 arg0;
    __u64 arg1;
    __u64 arg2;
    __u64 arg3;
    __u64 arg4;
    __u64 arg5;
    __u64 pid_generation;
    char path[ACTRAIL_FILE_PATH_ABI_MAX_BYTES];
    char secondary_path[ACTRAIL_FILE_PATH_ABI_MAX_BYTES];
} __attribute__((packed));

#endif
