#!/usr/bin/env python3
"""Run the real AcTrail fanotify permission-enforcement E2E."""

import argparse
import os
import select
import signal
import subprocess
import sys
import tempfile
import time
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bin-dir", default=os.environ.get("ACTRAIL_BIN_DIR", "target/release"))
    parser.add_argument("--daemon-ready-timeout-sec", type=float, default=10.0)
    parser.add_argument("--agent-timeout-sec", type=float, default=10.0)
    parser.add_argument("--drain-attempts", type=int, default=20)
    parser.add_argument("--drain-sleep-sec", type=float, default=0.2)
    return parser.parse_args()


def require_root() -> None:
    if os.geteuid() != 0:
        raise RuntimeError("fanotify permission events require root/CAP_SYS_ADMIN")


def require_binary(bin_dir: Path, name: str) -> Path:
    path = bin_dir / name
    if not path.exists():
        raise RuntimeError(f"missing binary {path}; build with cargo build --release")
    return path


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def operator_config(tmp: Path, rules_path: Path) -> str:
    return f"""# Generated by tests/enforcement/fanotify/run_e2e.py
socket_path = {tmp / "actrail.sock"}
socket_mode_octal = 660
pid_file = {tmp / "actraild.pid"}
storage_path = {tmp / "actrail.sqlite"}
web_listen_addr = 127.0.0.1:18080
web_request_read_timeout_ms = 1000
export_directory = {tmp / "export"}
log_path = {tmp / "actraild.log"}
diagnostic_log_level = info

graph_schema_version = manual-v1
allow_active_trace_snapshot = true
export_payload_bytes_enabled = false
export_payload_text_enabled = false

otel_live_export_enabled = false
otel_live_export_path = {tmp / "actrail-live-spans.otlp.jsonl"}
otel_live_export_overwrite_enabled = false
otel_live_export_queue_capacity = 1024
otel_live_export_flush_every_spans = 1

profile_name = fanotify-enforcement-e2e
required_capability = enforcement-file-permission-fanotify

ebpf_enabled = false
memlock_rlimit = inherit
tracked_process_max_entries = 4096
pending_operation_max_entries = 4096
event_ring_buffer_max_bytes = 1048576
file_path_capture_enabled = false
file_path_max_bytes = 255

payload_tls_enabled = false
payload_tls_capture_backend = seccomp-user-read
payload_tls_source = shared-library
payload_tls_resolver = openssl-symbols
payload_tls_library = openssl
payload_tls_library_path = auto
payload_tls_binary_path = disabled
payload_tls_pattern_path = disabled
payload_tls_max_segment_bytes = 4095
payload_tls_max_operation_bytes = 4194304
payload_tls_ring_buffer_bytes = 1048576
payload_tls_pending_operation_max_entries = 4096
payload_tls_seccomp_syscall = write
payload_tls_seccomp_syscall = writev
payload_tls_seccomp_syscall = sendto
payload_tls_seccomp_syscall = sendmsg
payload_tls_retention_max_bytes_per_trace = 10485760
payload_tls_redaction_policy = authorization-header
payload_tls_sync_runtime_library_path = auto
payload_tls_sync_event_socket_path = /tmp/actrail-tls-sync.sock
payload_tls_sync_socket_mode_octal = 660
payload_tls_sync_match_limit = 8

seccomp_notify_enabled = false
seccomp_notify_reserved_listener_fd = 253

process_seccomp_enabled = false
process_seccomp_syscall = execve
process_seccomp_syscall = execveat
process_seccomp_syscall = fork
process_seccomp_syscall = vfork
process_seccomp_syscall = clone
process_seccomp_syscall = clone3
process_seccomp_max_args = 64
process_seccomp_max_arg_bytes = 4096
process_seccomp_pending_max_entries = 4096

agent_invocation_enabled = false
agent_invocation_command = opencode
agent_invocation_command = .opencode
agent_invocation_command = claude

payload_stdio_enabled = false
payload_stdio_capture_stdin = false
payload_stdio_capture_stdout = true
payload_stdio_capture_stderr = true
payload_stdio_max_segment_bytes = 4095
payload_stdio_ring_buffer_bytes = 1048576
payload_stdio_pending_operation_max_entries = 4096
payload_stdio_stream_state_max_entries = 4096
payload_stdio_retention_max_bytes_per_trace = 10485760
payload_stdio_redaction_policy = authorization-header

payload_socket_enabled = false
payload_socket_capture_backend = bpf-copy-seccomp-fallback
payload_socket_max_segment_bytes = 4095
payload_socket_max_operation_bytes = 4194304
payload_socket_ring_buffer_bytes = 2097152
payload_socket_pending_operation_max_entries = 4096
payload_socket_stream_state_max_entries = 4096
payload_socket_retention_max_bytes_per_trace = 10485760
payload_socket_redaction_policy = authorization-header
payload_socket_http_sniff_max_bytes = 8192
payload_socket_seccomp_syscall = write
payload_socket_seccomp_syscall = sendto

application_protocol_enabled = false
application_protocol_http1_enabled = false
application_protocol_http2_enabled = false
application_http_capture_host = false
application_http_sse_enabled = false
application_http_sse_data_policy = disabled
application_http_sse_max_buffer_bytes = 1048576
application_http_sse_max_data_bytes = 4096
application_http2_max_frame_bytes = 16384
application_http2_max_connection_buffer_bytes = 1048576
application_http2_emit_data_preview = false
application_http2_max_data_preview_bytes = 4096

resource_metrics_enabled = false
resource_metrics_interval_ms = 1000
resource_metrics_include_children = true
resource_metrics_include_system = true
resource_metrics_cpu_alert_percent_millis = disabled
resource_metrics_memory_alert_rss_kb = disabled

provider_rules_enabled = false
provider_rules_path = /etc/actrail/provider-rules.conf
provider_unknown_provider_label = unknown

enforcement_enabled = true
enforcement_backend = fanotify
enforcement_scope = trace
enforcement_rules_path = {rules_path}
enforcement_default_decision = allow
enforcement_mark_strategy = parent-directories
enforcement_audit_enabled = true
enforcement_event_buffer_bytes = 65536

startup_wait_ms = 5000
shutdown_wait_ms = 5000
supervision_poll_interval_ms = 100
"""


def wait_for_daemon(process: subprocess.Popen[str], timeout_sec: float) -> None:
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        line = read_line_until(process, process.stdout, deadline)
        if line:
            print(line, end="")
            if "daemon listening" in line:
                return
        if process.poll() is not None:
            stderr = process.stderr.read()
            raise RuntimeError(f"actraild exited early: {stderr}")
    raise RuntimeError("actraild did not report readiness")


def read_agent_pid(process: subprocess.Popen[str], timeout_sec: float) -> int:
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        line = read_line_until(process, process.stdout, deadline)
        if line.startswith("agent_pid="):
            print(line, end="")
            return int(line.split("=", 1)[1])
        if line:
            print(line, end="")
        if process.poll() is not None:
            raise RuntimeError("agent exited before reporting pid")
    raise RuntimeError("agent did not report pid")


def run_checked(command: list[str]) -> str:
    result = subprocess.run(command, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(
            f"command failed: {' '.join(command)}\nstdout={result.stdout}\nstderr={result.stderr}"
        )
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    return result.stdout


def wait_for_agent_output(process: subprocess.Popen[str], timeout_sec: float) -> str:
    deadline = time.monotonic() + timeout_sec
    lines: list[str] = []
    while time.monotonic() < deadline:
        line = read_line_until(process, process.stdout, deadline)
        if line:
            print(line, end="")
            lines.append(line)
            if "denied=" in line:
                break
        if process.poll() is not None:
            break
    exit_code = process.wait(timeout=max(deadline - time.monotonic(), 0.1))
    output = "".join(lines)
    if exit_code != 0:
        raise RuntimeError(f"agent failed with exit={exit_code}: {output}")
    return output


def read_line_until(
    process: subprocess.Popen[str],
    stream,
    deadline: float,
) -> str:
    if stream is None:
        raise RuntimeError("process stream is not captured")
    remaining = deadline - time.monotonic()
    if remaining <= 0:
        return ""
    readable, _, _ = select.select([stream], [], [], remaining)
    if readable:
        return stream.readline()
    if process.poll() is not None:
        return stream.readline()
    return ""


def wait_for_enforcement_events(
    actrailctl: Path,
    actrailviewer: Path,
    config_path: Path,
    attempts: int,
    sleep_sec: float,
) -> str:
    for _ in range(attempts):
        run_checked([str(actrailctl), "--config", str(config_path), "list-traces"])
        output = run_checked(
            [str(actrailviewer), "events", "--config", str(config_path), "--trace-id", "1"]
        )
        if all(value in output for value in ["Enforcement", "allow-file", "deny-file"]):
            return output
        time.sleep(sleep_sec)
    raise RuntimeError("actrailviewer did not show expected enforcement events")


def stop_process(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return
    process.send_signal(signal.SIGTERM)
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


def main() -> int:
    args = parse_args()
    require_root()
    repo = Path.cwd()
    bin_dir = repo / args.bin_dir
    actraild = require_binary(bin_dir, "actraild")
    actrailctl = require_binary(bin_dir, "actrailctl")
    actrailviewer = require_binary(bin_dir, "actrailviewer")
    agent_script = repo / "tests" / "enforcement" / "fanotify" / "agent.py"

    with tempfile.TemporaryDirectory(prefix="actrail-fanotify-e2e-") as raw_tmp:
        tmp = Path(raw_tmp)
        allowed = tmp / "targets" / "allowed.txt"
        denied = tmp / "targets" / "denied.txt"
        rules = tmp / "rules.conf"
        config = tmp / "operator.conf"
        write_text(allowed, "allowed\n")
        write_text(denied, "denied\n")
        write_text(rules, f"allow-file allow open {allowed}\ndeny-file deny open {denied}\n")
        write_text(config, operator_config(tmp, rules))

        daemon = subprocess.Popen(
            [str(actraild), "--config", str(config), "run"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        try:
            wait_for_daemon(daemon, args.daemon_ready_timeout_sec)
            agent = subprocess.Popen(
                [
                    sys.executable,
                    str(agent_script),
                    "--allowed-path",
                    str(allowed),
                    "--denied-path",
                    str(denied),
                ],
                text=True,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            try:
                pid = read_agent_pid(agent, args.agent_timeout_sec)
                run_checked(
                    [
                        str(actrailctl),
                        "--config",
                        str(config),
                        "track-add",
                        "--pid",
                        str(pid),
                        "--name",
                        "fanotify-enforcement-e2e",
                    ]
                )
                agent.stdin.write("go\n")
                agent.stdin.flush()
                agent_output = wait_for_agent_output(agent, args.agent_timeout_sec)
                if "allowed=ok" not in agent_output:
                    raise RuntimeError("agent did not confirm allowed file access")
                if "denied=permission_denied" not in agent_output:
                    raise RuntimeError("agent did not confirm denied file access")
                viewer_output = wait_for_enforcement_events(
                    actrailctl,
                    actrailviewer,
                    config,
                    args.drain_attempts,
                    args.drain_sleep_sec,
                )
                if "decision=allow" not in viewer_output or "decision=deny" not in viewer_output:
                    raise RuntimeError("viewer output missed allow/deny decisions")
            finally:
                stop_process(agent)
        finally:
            stop_process(daemon)

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"fanotify e2e failed: {error}", file=sys.stderr)
        raise SystemExit(1)
