#!/usr/bin/env python3
"""Run the WASM ControlDecider fanotify graylist E2E."""

from __future__ import annotations

import argparse
import os
import select
import signal
import subprocess
import sys
import tempfile
import time
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
FIXTURE_DIR = ROOT / "tests/plugins/control-graylist"
MANIFEST = FIXTURE_DIR / "allow-on-gray.plugin.toml"
PLUGIN_CONFIG = FIXTURE_DIR / "allow-on-gray.config.toml"
INSTANCE = "wasm.graylist-allow"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bin-dir", default=os.environ.get("ACTRAIL_BIN_DIR", "target/release"))
    parser.add_argument("--daemon-ready-timeout-sec", type=float, default=10.0)
    parser.add_argument("--agent-timeout-sec", type=float, default=10.0)
    parser.add_argument("--drain-attempts", type=int, default=20)
    parser.add_argument("--drain-sleep-sec", type=float, default=0.2)
    return parser.parse_args()


def require_root() -> None:
    if os.geteuid() != 0:
        raise RuntimeError("fanotify permission events require root/CAP_SYS_ADMIN")


def require_binary(bin_dir: Path, name: str) -> Path:
    path = bin_dir / name
    if not path.exists():
        raise RuntimeError(f"missing binary {path}; build with cargo build --release")
    return path


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def operator_config(tmp: Path, rules_path: Path) -> str:
    return f"""# Generated by tests/plugins/control-graylist/run_e2e.py
[control]
socket_path = "{tmp / 'actrail.sock'}"
socket_mode_octal = "660"
pending_connection_max = 256
pid_file = "{tmp / 'actraild.pid'}"
log_path = "{tmp / 'actraild.log'}"
diagnostic_log_level = "info"

[storage]
backend = "sqlite"

[storage.sqlite]
path = "{tmp / 'actrail.sqlite'}"
busy_timeout_ms = 5000

[web]
listen_addr = "127.0.0.1:18080"
request_read_timeout_ms = "1000"

[export.snapshot]
graph_schema_version = "manual-v1"
allow_active_trace_snapshot = true
directory = "{tmp / 'export'}"
payload_bytes_enabled = false
payload_text_enabled = false

[export.runtime]
enabled = false

[[export.runtime.routes]]
name = "live-otel"
kind = "otel-jsonl"
delivery = "best-effort"
enabled = true

[export.runtime.routes.otel_jsonl]
path = "{tmp / 'actrail-live-spans.otlp.jsonl'}"
overwrite_enabled = false
queue_capacity = 1024
flush_every_spans = 1

[capture]
profile_name = "control-graylist-plugin-e2e"
capabilities = ["enforcement-file-permission-fanotify"]

[ebpf]
enabled = false
memlock_rlimit = "inherit"
tracked_process_max_entries = 4096
pending_operation_max_entries = 4096
suppressed_fd_max_entries = 4096
suppressed_fd_index_slots_per_process = 64
event_ring_buffer_max_bytes = 1048576
file_path_capture_enabled = false
file_path_max_bytes = 255

[payload.tls]
enabled = false
capture_backend = "tls-sync"
source = "auto"
resolver = "auto"
library = "auto"
library_path = "auto"
binary_path = "disabled"
pattern_path = "disabled"
max_segment_bytes = 4095
max_operation_bytes = 4194304
ring_buffer_bytes = 1048576
pending_operation_max_entries = 4096
retention_max_bytes_per_trace = 10485760
redaction_policy = "authorization-header"
sync_runtime_library_path = "auto"
sync_event_socket_path = "/tmp/actrail-test-control-graylist-tls-sync.sock"
sync_socket_mode_octal = "660"
sync_match_limit = 8
seccomp_syscalls = ["write", "writev", "sendto", "sendmsg"]

[payload.stdio]
enabled = false
capture_stdin = false
capture_stdout = true
capture_stderr = true
stdin_storage_mode = "full"
stdout_storage_mode = "drop"
stderr_storage_mode = "metadata-only"
max_segment_bytes = 4095
ring_buffer_bytes = 1048576
pending_operation_max_entries = 4096
stream_state_max_entries = 4096
retention_max_bytes_per_trace = 10485760
redaction_policy = "authorization-header"

[payload.socket]
enabled = false
capture_backend = "bpf-copy-seccomp-fallback"
max_segment_bytes = 4095
max_operation_bytes = 4194304
ring_buffer_bytes = 2097152
pending_operation_max_entries = 4096
stream_state_max_entries = 4096
retention_max_bytes_per_trace = 10485760
redaction_policy = "authorization-header"
http_sniff_max_bytes = 8192
seccomp_syscalls = ["write", "sendto"]

[seccomp_notify]
enabled = false
reserved_listener_fd = 253

[process_seccomp]
enabled = false
syscalls = ["execve", "execveat", "fork", "vfork", "clone", "clone3"]
max_args = 64
max_arg_bytes = 4096
pending_max_entries = 4096

[agent_invocation]
enabled = false
commands = ["opencode", ".opencode", "claude"]

[application]
enabled = false
http1_enabled = false
http2_enabled = false

[application.http]
capture_host = false
sse_enabled = false
sse_data_policy = "disabled"
sse_max_buffer_bytes = 4194304

[application.http2]
max_frame_bytes = 16384
max_connection_buffer_bytes = 1048576
emit_data_preview = false
max_data_preview_bytes = 4096

[resource_metrics]
enabled = false
interval_ms = 1000
include_children = true
include_system = true
cpu_alert_percent_millis = "disabled"
memory_alert_rss_kb = "disabled"

[provider]
rules_enabled = false
rules_path = "/etc/actrail/provider-rules.conf"
unknown_provider_label = "unknown"

[enforcement]
enabled = true
backend = "fanotify"
scope = "trace"
rules_path = "{rules_path}"
default_decision = "allow"
mark_strategy = "parent-directories"
audit_enabled = true
event_buffer_bytes = 65536

[supervision]
startup_wait_ms = 5000
shutdown_wait_ms = 5000
poll_interval_ms = 100
"""


def wait_for_daemon(process: subprocess.Popen[str], timeout_sec: float) -> None:
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        line = read_line_until(process, process.stdout, deadline)
        if line:
            print(line, end="")
            if "daemon listening" in line:
                return
        if process.poll() is not None:
            stderr = process.stderr.read() if process.stderr else ""
            raise RuntimeError(f"actraild exited early: {stderr}")
    raise RuntimeError("actraild did not report readiness")


def read_agent_pid(process: subprocess.Popen[str], timeout_sec: float) -> int:
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        line = read_line_until(process, process.stdout, deadline)
        if line.startswith("agent_pid="):
            print(line, end="")
            return int(line.split("=", 1)[1])
        if line:
            print(line, end="")
        if process.poll() is not None:
            raise RuntimeError("agent exited before reporting pid")
    raise RuntimeError("agent did not report pid")


def run_checked(command: list[str]) -> str:
    result = subprocess.run(command, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(
            f"command failed: {' '.join(command)}\nstdout={result.stdout}\nstderr={result.stderr}"
        )
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    return result.stdout


def parse_status_fields(raw: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for line in raw.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        fields[key.strip()] = value.strip()
    return fields


def wait_for_agent_output(process: subprocess.Popen[str], timeout_sec: float) -> str:
    deadline = time.monotonic() + timeout_sec
    lines: list[str] = []
    while time.monotonic() < deadline:
        line = read_line_until(process, process.stdout, deadline)
        if line:
            print(line, end="")
            lines.append(line)
            if "denied=" in line:
                break
        if process.poll() is not None:
            break
    exit_code = process.wait(timeout=max(deadline - time.monotonic(), 0.1))
    output = "".join(lines)
    if exit_code != 0:
        stderr = process.stderr.read() if process.stderr else ""
        raise RuntimeError(f"agent failed with exit={exit_code}: {output}{stderr}")
    return output


def read_line_until(process: subprocess.Popen[str], stream, deadline: float) -> str:
    if stream is None:
        raise RuntimeError("process stream is not captured")
    remaining = deadline - time.monotonic()
    if remaining <= 0:
        return ""
    readable, _, _ = select.select([stream], [], [], remaining)
    if readable:
        return stream.readline()
    if process.poll() is not None:
        return stream.readline()
    return ""


def wait_for_enforcement_events(
    actrailctl: Path,
    actrailviewer: Path,
    config_path: Path,
    attempts: int,
    sleep_sec: float,
) -> str:
    expected = [
        "Enforcement",
        "allow-file",
        "gray-file",
        "deny-file",
        "decision_source=sync-plugin",
        f"plugin_instance={INSTANCE}",
        "plugin_timeout_ms=5000",
        "plugin_concurrency_limit=1",
    ]
    for _ in range(attempts):
        run_checked([str(actrailctl), "--config", str(config_path), "list-traces"])
        output = run_checked(
            [str(actrailviewer), "events", "--config", str(config_path), "--trace-id", "1"]
        )
        if all(value in output for value in expected):
            return output
        time.sleep(sleep_sec)
    raise RuntimeError("actrailviewer did not show expected graylist plugin events")


def stop_process(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return
    process.send_signal(signal.SIGTERM)
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


def main() -> int:
    args = parse_args()
    require_root()
    bin_dir = ROOT / args.bin_dir
    actraild = require_binary(bin_dir, "actraild")
    actrailctl = require_binary(bin_dir, "actrailctl")
    actrailviewer = require_binary(bin_dir, "actrailviewer")
    agent_script = FIXTURE_DIR / "agent.py"

    with tempfile.TemporaryDirectory(prefix="actrail-control-graylist-e2e-") as raw_tmp:
        tmp = Path(raw_tmp)
        allowed = tmp / "targets" / "allowed.txt"
        gray = tmp / "targets" / "gray.txt"
        denied = tmp / "targets" / "denied.txt"
        rules = tmp / "rules.conf"
        config = tmp / "operator.conf"
        write_text(allowed, "allowed\n")
        write_text(gray, "gray\n")
        write_text(denied, "denied\n")
        write_text(
            rules,
            "\n".join(
                [
                    f"allow-file allow open {allowed}",
                    f"gray-file gray sync-plugin {INSTANCE} timeout-ms 5000 concurrency 1 fallback deny open {gray}",
                    f"deny-file deny open {denied}",
                    "",
                ]
            ),
        )
        write_text(config, operator_config(tmp, rules))

        daemon = subprocess.Popen(
            [str(actraild), "--config", str(config), "run"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        try:
            wait_for_daemon(daemon, args.daemon_ready_timeout_sec)
            run_checked(
                [
                    str(actraild),
                    "--config",
                    str(config),
                    "plugin",
                    "load",
                    "--manifest",
                    str(MANIFEST),
                    "--plugin-config",
                    str(PLUGIN_CONFIG),
                    "--instance",
                    INSTANCE,
                ]
            )
            agent = subprocess.Popen(
                [
                    sys.executable,
                    str(agent_script),
                    "--allowed-path",
                    str(allowed),
                    "--gray-path",
                    str(gray),
                    "--denied-path",
                    str(denied),
                ],
                text=True,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            try:
                pid = read_agent_pid(agent, args.agent_timeout_sec)
                run_checked(
                    [
                        str(actrailctl),
                        "--config",
                        str(config),
                        "track-add",
                        "--pid",
                        str(pid),
                        "--name",
                        "control-graylist-plugin-e2e",
                    ]
                )
                if agent.stdin is None:
                    raise RuntimeError("agent stdin is not captured")
                agent.stdin.write("go\n")
                agent.stdin.flush()
                agent_output = wait_for_agent_output(agent, args.agent_timeout_sec)
                if "allowed=ok" not in agent_output:
                    raise RuntimeError("agent did not confirm allow fast path")
                if "gray=ok" not in agent_output:
                    raise RuntimeError("agent did not confirm gray plugin allow")
                if "denied=permission_denied" not in agent_output:
                    raise RuntimeError("agent did not confirm deny fast path")
                viewer_output = wait_for_enforcement_events(
                    actrailctl,
                    actrailviewer,
                    config,
                    args.drain_attempts,
                    args.drain_sleep_sec,
                )
                if "decision=allow" not in viewer_output or "decision=deny" not in viewer_output:
                    raise RuntimeError("viewer output missed allow/deny decisions")
                status = parse_status_fields(
                    run_checked(
                        [
                            str(actraild),
                            "--config",
                            str(config),
                            "plugin",
                            "status",
                            "--instance",
                            INSTANCE,
                        ]
                    )
                )
                if status.get("purpose") != "control-decider":
                    raise RuntimeError(f"control plugin status missed purpose\n{status}")
                if status.get("runtime") != "wasm":
                    raise RuntimeError(f"control plugin status missed runtime\n{status}")
                observed = int(status.get("observed_records", "0"))
                if observed <= 0:
                    raise RuntimeError(f"control plugin did not record decisions\n{status}")
                run_checked(
                    [
                        str(actraild),
                        "--config",
                        str(config),
                        "plugin",
                        "unload",
                        "--instance",
                        INSTANCE,
                    ]
                )
            finally:
                stop_process(agent)
        finally:
            stop_process(daemon)

    print(f"control_graylist_plugin_instance={INSTANCE}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"control graylist e2e failed: {error}", file=sys.stderr)
        raise SystemExit(1)
