#ifndef DYN_TLS_WORKLOAD_EXIT_H
#define DYN_TLS_WORKLOAD_EXIT_H

enum DynamicTlsWorkloadExit {
  DYN_TLS_EXIT_USAGE = 2,
  DYN_TLS_EXIT_DLOPEN = 3,
  DYN_TLS_EXIT_DLSYM = 4,
  DYN_TLS_EXIT_SSL_WRITE = 5,
  DYN_TLS_EXIT_SSL_WRITE_EX2 = 6,
  DYN_TLS_EXIT_SSL_READ = 7,
  DYN_TLS_EXIT_POST_PAYLOAD_SLEEP = 8,
  DYN_TLS_EXIT_SSL_WRITE_BRANCH = 9,
};

#endif
