#!/usr/bin/env python3
"""Run network-action ControlDecider E2E with a real launched workload."""

from __future__ import annotations

import argparse
import os
import select
import signal
import socket
import sqlite3
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
FIXTURE_DIR = ROOT / "tests/plugins/network-action"
INSTANCE = "wasm.network-deny"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bin-dir", default=os.environ.get("ACTRAIL_BIN_DIR", "target/release"))
    parser.add_argument("--daemon-ready-timeout-sec", type=float, default=10.0)
    parser.add_argument("--agent-timeout-sec", type=float, default=10.0)
    parser.add_argument("--drain-attempts", type=int, default=20)
    parser.add_argument("--drain-sleep-sec", type=float, default=0.2)
    return parser.parse_args()


def require_root() -> None:
    if os.geteuid() != 0:
        raise RuntimeError("network-action control E2E requires root for seccomp setup")


def require_binary(bin_dir: Path, name: str) -> Path:
    path = bin_dir / name
    if not path.exists():
        raise RuntimeError(f"missing binary {path}; build with cargo build --release")
    return path


def write_text(path: Path, text: str, mode: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    if mode is not None:
        path.chmod(mode)


class TcpProbeServer:
    def __init__(self, name: str) -> None:
        self.name = name
        self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._sock.bind(("127.0.0.1", 0))
        self._sock.listen(8)
        self._sock.settimeout(0.2)
        self.port = int(self._sock.getsockname()[1])
        self.accepted: list[bytes] = []
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._serve, name=f"{name}-server", daemon=True)

    def start(self) -> None:
        self._thread.start()

    def close(self) -> None:
        self._stop.set()
        try:
            self._sock.close()
        finally:
            self._thread.join(timeout=2.0)

    def _serve(self) -> None:
        while not self._stop.is_set():
            try:
                conn, _ = self._sock.accept()
            except socket.timeout:
                continue
            except OSError:
                return
            with conn:
                data = conn.recv(64)
                self.accepted.append(data)
                conn.sendall(b"ok")


def operator_config(tmp: Path, rules_path: Path) -> str:
    return f"""# Generated by tests/plugins/network-action/run_e2e.py
[control]
socket_path = "{tmp / 'actrail.sock'}"
socket_mode_octal = "660"
pending_connection_max = 256
pid_file = "{tmp / 'actraild.pid'}"
log_path = "{tmp / 'actraild.log'}"
diagnostic_log_level = "info"

[storage]
backend = "sqlite"

[storage.sqlite]
path = "{tmp / 'actrail.sqlite'}"
busy_timeout_ms = 5000

[web]
listen_addr = "127.0.0.1:18080"
request_read_timeout_ms = "1000"

[export.snapshot]
graph_schema_version = "manual-v1"
allow_active_trace_snapshot = true
directory = "{tmp / 'export'}"
payload_bytes_enabled = false
payload_text_enabled = false

[export.runtime]
enabled = false

[[export.runtime.routes]]
name = "live-otel"
kind = "otel-jsonl"
delivery = "best-effort"
enabled = false

[export.runtime.routes.otel_jsonl]
path = "{tmp / 'actrail-live-spans.otlp.jsonl'}"
overwrite_enabled = false
queue_capacity = 128
flush_every_spans = 1

[capture]
profile_name = "network-action-plugin-e2e"
capabilities = ["proc-exec-context"]

[ebpf]
enabled = false
memlock_rlimit = "inherit"
tracked_process_max_entries = 1024
pending_operation_max_entries = 1024
suppressed_fd_max_entries = 1024
suppressed_fd_index_slots_per_process = 64
event_ring_buffer_max_bytes = 1048576
file_path_capture_enabled = false
file_path_max_bytes = 255

[payload.tls]
enabled = false
capture_backend = "tls-sync"
source = "auto"
resolver = "auto"
library = "auto"
library_path = "auto"
binary_path = "disabled"
pattern_path = "disabled"
max_segment_bytes = 4095
max_operation_bytes = 4194304
ring_buffer_bytes = 1048576
pending_operation_max_entries = 1024
retention_max_bytes_per_trace = 1048576
redaction_policy = "disabled"
sync_runtime_library_path = "auto"
sync_event_socket_path = "{tmp / 'tls-sync.sock'}"
sync_socket_mode_octal = "660"
sync_match_limit = 8
seccomp_syscalls = ["write", "writev", "sendto", "sendmsg"]

[payload.stdio]
enabled = false
capture_stdin = false
capture_stdout = true
capture_stderr = true
stdin_storage_mode = "metadata-only"
stdout_storage_mode = "metadata-only"
stderr_storage_mode = "metadata-only"
max_segment_bytes = 4095
ring_buffer_bytes = 1048576
pending_operation_max_entries = 1024
stream_state_max_entries = 1024
retention_max_bytes_per_trace = 1048576
redaction_policy = "disabled"

[payload.socket]
enabled = false
capture_backend = "bpf-copy-seccomp-fallback"
max_segment_bytes = 4095
max_operation_bytes = 4194304
ring_buffer_bytes = 1048576
pending_operation_max_entries = 1024
stream_state_max_entries = 1024
retention_max_bytes_per_trace = 1048576
redaction_policy = "disabled"
http_sniff_max_bytes = 8192
seccomp_syscalls = ["write", "sendto"]

[seccomp_notify]
enabled = true
reserved_listener_fd = 253

[process_seccomp]
enabled = true
syscalls = ["execve", "execveat", "fork", "vfork", "clone", "clone3"]
max_args = 64
max_arg_bytes = 4096
pending_max_entries = 1024

[network_control]
enabled = true
rules_path = "{rules_path}"

[agent_invocation]
enabled = false
commands = []

[application]
enabled = false
http1_enabled = false
http2_enabled = false

[application.http]
capture_host = false
sse_enabled = false
sse_data_policy = "disabled"
sse_max_buffer_bytes = 4194304
sse_max_data_bytes = 4096

[application.http2]
max_frame_bytes = 16384
max_connection_buffer_bytes = 1048576
emit_data_preview = false
max_data_preview_bytes = 4096

[resource_metrics]
enabled = false
interval_ms = 1000
include_children = true
include_system = true
cpu_alert_percent_millis = "disabled"
memory_alert_rss_kb = "disabled"

[provider]
rules_enabled = false
rules_path = "/etc/actrail/provider-rules.conf"
unknown_provider_label = "unknown"

[enforcement]
enabled = false
backend = "fanotify"
scope = "trace"
rules_path = "{tmp / 'unused-enforcement-rules.conf'}"
default_decision = "allow"
mark_strategy = "parent-directories"
audit_enabled = false
event_buffer_bytes = 65536

[command_control]
enabled = false
rules_path = "{tmp / 'unused-command-rules.conf'}"

[supervision]
startup_wait_ms = 5000
shutdown_wait_ms = 5000
poll_interval_ms = 100
"""


def read_line_until(process: subprocess.Popen[str], stream, deadline: float) -> str:
    remaining = deadline - time.monotonic()
    if remaining <= 0:
        return ""
    ready, _, _ = select.select([stream], [], [], remaining)
    if not ready:
        return ""
    return stream.readline()


def wait_for_daemon(process: subprocess.Popen[str], timeout_sec: float) -> None:
    deadline = time.monotonic() + timeout_sec
    stderr_tail: list[str] = []
    while time.monotonic() < deadline:
        if process.stdout is not None:
            line = read_line_until(process, process.stdout, min(deadline, time.monotonic() + 0.2))
            if line:
                print(line, end="")
                if "daemon listening" in line:
                    return
        if process.poll() is not None:
            if process.stderr is not None:
                stderr_tail.append(process.stderr.read())
            raise RuntimeError(f"actraild exited early: {''.join(stderr_tail)}")
    raise RuntimeError("daemon did not become ready")


def run_checked(command: list[str]) -> str:
    result = subprocess.run(command, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(
            f"command failed rc={result.returncode}: {' '.join(command)}\nstdout={result.stdout}\nstderr={result.stderr}"
        )
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    return result.stdout


def decode_map(raw: str) -> dict[str, str]:
    def unescape(value: str) -> str:
        output: list[str] = []
        index = 0
        while index < len(value):
            char = value[index]
            if char == "\\" and index + 1 < len(value):
                escaped = value[index + 1]
                if escaped == "n":
                    output.append("\n")
                elif escaped == "e":
                    output.append("=")
                elif escaped == "\\":
                    output.append("\\")
                else:
                    output.append("\\")
                    output.append(escaped)
                index += 2
            else:
                output.append(char)
                index += 1
        return "".join(output)

    fields: dict[str, str] = {}
    for line in raw.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        fields[unescape(key)] = unescape(value)
    return fields


def wait_for_agent_pid(process: subprocess.Popen[str], timeout_sec: float) -> int:
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        line = read_line_until(process, process.stdout, deadline)
        if line.startswith("agent_pid="):
            print(line, end="")
            return int(line.split("=", 1)[1])
        if line:
            print(line, end="")
        if process.poll() is not None:
            raise RuntimeError("agent exited before reporting pid")
    raise RuntimeError("agent did not report pid")


def wait_for_agent_output(process: subprocess.Popen[str], timeout_sec: float) -> str:
    deadline = time.monotonic() + timeout_sec
    lines: list[str] = []
    while time.monotonic() < deadline:
        line = read_line_until(process, process.stdout, deadline)
        if line:
            print(line, end="")
            lines.append(line)
            if "denied_connect=" in line:
                break
        if process.poll() is not None:
            break
    output = "".join(lines)
    exit_code = process.wait(timeout=max(deadline - time.monotonic(), 0.1))
    if exit_code != 0:
        stderr = process.stderr.read() if process.stderr else ""
        raise RuntimeError(f"agent failed exit={exit_code}\nstdout={output}\nstderr={stderr}")
    return output


def wait_for_network_control_event(
    actrailctl: Path,
    config: Path,
    storage_path: Path,
    expected_endpoint: str,
    attempts: int,
    sleep_sec: float,
) -> dict[str, str]:
    for _ in range(attempts):
        run_checked([str(actrailctl), "--config", str(config), "list-traces"])
        with sqlite3.connect(storage_path) as connection:
            rows = connection.execute(
                "select payload_fields from events where trace_id = 1 and payload_variant = 'net'"
            ).fetchall()
        for (payload_fields,) in rows:
            fields = decode_map(payload_fields)
            if fields.get("remote") != expected_endpoint:
                continue
            metadata = decode_map(fields.get("metadata", ""))
            if (
                metadata.get("subject") == "network-action"
                and metadata.get("operation") == "connect"
                and metadata.get("decision_source") == "sync-plugin"
                and metadata.get("plugin_instance") == INSTANCE
                and metadata.get("rule_id") == "network-deny"
                and metadata.get("decision") == "deny"
            ):
                return metadata
        time.sleep(sleep_sec)
    raise RuntimeError("SQLite did not show expected network-action control event")


def parse_status_fields(output: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for line in output.splitlines():
        for item in line.split():
            if "=" in item:
                key, value = item.split("=", 1)
                fields[key] = value
    return fields


def stop_process(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return
    process.send_signal(signal.SIGTERM)
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


def main() -> int:
    args = parse_args()
    require_root()
    bin_dir = ROOT / args.bin_dir
    actraild = require_binary(bin_dir, "actraild")
    actrailctl = require_binary(bin_dir, "actrailctl")
    agent_script = FIXTURE_DIR / "agent.py"

    allowed_server = TcpProbeServer("allowed")
    denied_server = TcpProbeServer("denied")
    allowed_server.start()
    denied_server.start()
    try:
        with tempfile.TemporaryDirectory(prefix="actrail-network-action-e2e-") as raw_tmp:
            tmp = Path(raw_tmp)
            rules = tmp / "network-rules.conf"
            config = tmp / "operator.conf"
            denied_endpoint = f"127.0.0.1:{denied_server.port}"
            write_text(
                rules,
                f"network-deny sync-plugin {INSTANCE} timeout-ms 5000 concurrency 1 fallback deny connect {denied_endpoint}\n",
            )
            write_text(config, operator_config(tmp, rules))
            write_text(tmp / "unused-enforcement-rules.conf", "")
            write_text(tmp / "unused-command-rules.conf", "")

            daemon = subprocess.Popen(
                [str(actraild), "--config", str(config), "run"],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            try:
                wait_for_daemon(daemon, args.daemon_ready_timeout_sec)
                run_checked(
                    [
                        str(actraild),
                        "--config",
                        str(config),
                        "plugin",
                        "load",
                        "--manifest",
                        str(FIXTURE_DIR / "deny-network.plugin.toml"),
                        "--instance",
                        INSTANCE,
                    ]
                )
                agent = subprocess.Popen(
                    [
                        str(actrailctl),
                        "--config",
                        str(config),
                        "launch",
                        "--name",
                        "network-action-control-plugin-e2e",
                        "--",
                        sys.executable,
                        str(agent_script),
                        "--allowed-port",
                        str(allowed_server.port),
                        "--denied-port",
                        str(denied_server.port),
                    ],
                    text=True,
                    stdin=subprocess.PIPE,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                )
                try:
                    wait_for_agent_pid(agent, args.agent_timeout_sec)
                    if agent.stdin is None:
                        raise RuntimeError("agent stdin is not captured")
                    agent.stdin.write("go\n")
                    agent.stdin.flush()
                    output = wait_for_agent_output(agent, args.agent_timeout_sec)
                finally:
                    stop_process(agent)
                if "allowed_connect=ok" not in output or "denied_connect=permission_denied" not in output:
                    raise RuntimeError(f"agent output missed expected markers: {output}")
                if allowed_server.accepted != [b"allowed"]:
                    raise RuntimeError(f"allowed server did not receive exactly one request: {allowed_server.accepted!r}")
                if denied_server.accepted:
                    raise RuntimeError(f"denied server received data despite plugin denial: {denied_server.accepted!r}")
                wait_for_network_control_event(
                    actrailctl,
                    config,
                    tmp / "actrail.sqlite",
                    denied_endpoint,
                    args.drain_attempts,
                    args.drain_sleep_sec,
                )
                status = parse_status_fields(
                    run_checked(
                        [
                            str(actraild),
                            "--config",
                            str(config),
                            "plugin",
                            "status",
                            "--instance",
                            INSTANCE,
                        ]
                    )
                )
                if status.get("purpose") != "control-decider":
                    raise RuntimeError(f"plugin status missed purpose: {status}")
                if int(status.get("observed_records", "0")) != 1:
                    raise RuntimeError(f"plugin should observe exactly one network decision: {status}")
            finally:
                stop_process(daemon)
    finally:
        allowed_server.close()
        denied_server.close()
    print("network_action_control_e2e=ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
