macro_rules! metadata_key_codebook {
    ($($code:literal => $key:literal),+ $(,)?) => {
        pub(super) struct MetadataKeyCodebook;

        impl MetadataKeyCodebook {
            pub(super) fn code(key: &str) -> Option<u8> {
                match key {
                    $($key => Some($code),)+
                    _ => None,
                }
            }

            pub(super) fn key(code: u8) -> Option<&'static str> {
                match code {
                    $($code => Some($key),)+
                    _ => None,
                }
            }
        }
    };
}

metadata_key_codebook! {
    1 => "content_length",
    2 => "content_type",
    3 => "data_preview",
    4 => "data_preview_omitted",
    5 => "data_preview_truncated",
    6 => "data_size",
    7 => "data_truncated",
    8 => "direction",
    9 => "endpoint_source",
    10 => "endpoint_unresolved",
    11 => "event",
    12 => "exec_filename",
    13 => "exec_filename_truncated",
    14 => "executable",
    15 => "exit_code",
    16 => "fd",
    17 => "flags",
    18 => "frame_type",
    19 => "frame_type_id",
    20 => "h2",
    21 => "host",
    22 => "http.body_json_state",
    23 => "length",
    24 => "method",
    25 => "operation",
    26 => "payload.captured_size",
    27 => "payload.omitted_size",
    28 => "payload.original_size",
    29 => "payload.summary.protocol",
    30 => "payload.summary.reason",
    31 => "payload.truncation",
    32 => "payload_segment_id",
    33 => "payload_sequence",
    34 => "reason",
    35 => "requested_size",
    36 => "result",
    37 => "signal",
    38 => "source_boundary",
    39 => "status_code",
    40 => "stream_id",
    41 => "stream_key",
    42 => "syscall_family",
    43 => "target",
    44 => "target_group",
    45 => "target_pid",
    46 => "transfer_encoding",
    47 => "args_truncated",
    48 => "argv",
    49 => "argv_count",
    50 => "bytes_read",
    51 => "clone.flags",
    52 => "clone.thread",
    53 => "clone3.args_ptr",
    54 => "clone3.args_size",
    55 => "command_line",
    56 => "env_captured",
    57 => "errno",
    58 => "error_count",
    59 => "exec.attempt_id",
    60 => "exec.capture_flags",
    61 => "exec.path",
    62 => "exec.result",
    63 => "execveat.dirfd",
    64 => "execveat.flags",
    65 => "fast_path",
    66 => "fd_creation_requested",
    67 => "fd_target",
    68 => "fd_target_kind",
    69 => "fd_target_source",
    70 => "first_ktime_ns",
    71 => "fork.attempt_id",
    72 => "fork.capture_flags",
    73 => "last_ktime_ns",
    74 => "path_captured_size",
    75 => "path_max_bytes",
    76 => "path_resolution",
    77 => "path_truncated",
    78 => "raw_path",
    79 => "read_count",
    80 => "shutdown_how",
    81 => "size",
    82 => "syscall",
    83 => "target_kernel_tid",
    84 => "aggregated",
    85 => "cnt",
    86 => "exec_filename_source",
    87 => "path_read_fault",
    88 => "payload.capture_incomplete",
    89 => "payload.operation_captured_size",
    90 => "payload.operation_completion_state",
    91 => "payload.operation_original_size",
    92 => "target_path",
    93 => "target_path_captured_size",
    94 => "target_path_read_fault",
    95 => "target_path_resolution",
    96 => "target_path_truncated",
    97 => "address_hint",
    98 => "dirfd",
    99 => "first_fd",
    100 => "how_size",
    101 => "last_fd",
    102 => "mapped_address",
    103 => "mode",
    104 => "new_dirfd",
    105 => "offset",
    106 => "old_dirfd",
    107 => "protection",
    108 => "raw_target_path",
    109 => "resolve",
    110 => "shared",
    111 => "source_fd",
    112 => "target_fd",
    113 => "truncate_source",
}
